---

EDXAPP_EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'

EDXAPP_TECH_SUPPORT_EMAIL: "{{ EDXAPP_DEFAULT_FROM_EMAIL }}"
EDXAPP_CONTACT_EMAIL: "{{ EDXAPP_DEFAULT_FROM_EMAIL }}"
EDXAPP_BUGS_EMAIL: "{{ EDXAPP_DEFAULT_FROM_EMAIL }}"
EDXAPP_DEFAULT_FEEDBACK_EMAIL: "{{ EDXAPP_DEFAULT_FROM_EMAIL }}"
EDXAPP_DEFAULT_SERVER_EMAIL: "{{ EDXAPP_DEFAULT_FROM_EMAIL }}"
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: "{{ EDXAPP_DEFAULT_FROM_EMAIL }}"
EDXAPP_PAYMENT_SUPPORT_EMAIL: "{{ EDXAPP_DEFAULT_FROM_EMAIL }}"

ANALYTICS_API_EMAIL_HOST_PASSWORD: "{{ EDXAPP_EMAIL_HOST_PASSWORD }}"

INSIGHTS_EMAIL_HOST_PASSWORD: "{{ EDXAPP_EMAIL_HOST_PASSWORD }}"

POSTFIX_QUEUE_EXTERNAL_SMTP_HOST: "{{ EDXAPP_EMAIL_HOST }}"
POSTFIX_QUEUE_EXTERNAL_SMTP_USER: "{{ EDXAPP_EMAIL_HOST_USER }}"
POSTFIX_QUEUE_EXTERNAL_SMTP_PASSWORD: "{{ EDXAPP_EMAIL_HOST_PASSWORD }}"
POSTFIX_QUEUE_EXTERNAL_SMTP_PORT: "{{ EDXAPP_EMAIL_PORT }}"

DISCOVERY_EMAIL_HOST: 'localhost'
DISCOVERY_EMAIL_PORT: 25
DISCOVERY_EMAIL_USE_TLS: False
DISCOVERY_EMAIL_HOST_USER: ''
DISCOVERY_EMAIL_HOST_PASSWORD: "{{ EDXAPP_EMAIL_HOST_PASSWORD }}"

SPLUNK_HOSTNAME: splunk.example.com
SPLUNK_SMTP_SERVER: "{{ EDXAPP_EMAIL_HOST }}"
SPLUNK_SMTP_USERNAME: "{{ EDXAPP_EMAIL_HOST_USER }}"
SPLUNK_SMTP_PASSWORD: "{{ EDXAPP_EMAIL_HOST_PASSWORD }}"
SPLUNK_FROM_ADDRESS: "{{ EDXAPP_EMAIL_HOST_USER }}"
SPLUNK_EMAIL_FOOTER: "Generated by {{ SPLUNK_HOSTNAME }}"
SPLUNK_SSL_HOSTNAME: splunk.example.com:443

